Fcep 42 initial app structure
DEFRA/ffc-ce-admin-web pull request #4
Opened 2020-01-10 16:15 UTC by jaucourt

https://eaflood.atlassian.net/browse/FCEP-42

Initial app structure and CI setup

2020-01-10 17:36 UTC, Matthew-Collins-Defra requested changes

2020-01-10 17:36 UTC, Matthew-Collins-Defra commented on package.json
> +  "description": "Digital service for calculation engine.",
This should be different from the user front end.
`Admin interface for the calculation engine digital service`

2020-01-10 17:36 UTC, Matthew-Collins-Defra commented on package.json
> +    "Phil Benson phil.benson@defra.gov.uk"
The email addresses need angle brackets around them. <>
`Matthew Collins <matthew.collins@defra.gov.uk>`
Trivial thing to fix, but while new people are being added it's best to get it right.

2020-01-10 17:36 UTC, Matthew-Collins-Defra commented on server/views/home.njk
> +      }) }}
I think this should be different from the User front end. Just some mention of "Admin interface" see we can tell that it's a different service from the other.

2020-01-13 16:06 UTC, markysoft requested changes
Looks good, mostly minor changes - a couple of handlers to move, some asyncs from the base project that can be deleted, and the ingress URL needs to be made consistent in the Jenkins file, and potentially shortened.

2020-01-13 16:06 UTC, markysoft commented on Jenkinsfile
> +      /ingress.endpoint="ffc-ce-admin-web-$containerTag"/,
the ingress endpoint is still pointing to `ffc-ce-admin-web-$containerTag` which is quite long and can cause issues in EKS, though it seems to be working at the moment.

This is different from the URL message shown after the Helm deployment, which is `ffc-aweb-$containerTag`

This should change so they are both the same, I'd suggest 'ce-admin-$containerTag'.
The `ffc` is present in the rest of the URL `ffc.aws-int.defra.cloud`, and web is a bit redundant.

2020-01-13 16:06 UTC, markysoft commented on helm/ffc-ce-admin-web/jenkins-aws.yaml
> +  endPoint: ffc-ce-admin-web
this will be the URL the master branch is deployed to after a merge. The length might cause issues with the ALB, perhaps use `ce-admin` instead.

2020-01-13 16:06 UTC, markysoft commented on scripts/test
> +docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --force-recreate  --exit-code-from ffc-ce-admin-web
similarly there's a slightly different version available now in ffc-ce-web

2020-01-13 16:06 UTC, markysoft commented on server/routes/public.js
> +  }
the handlers are in the options rather than at the top level here, which works at the moment, but doesn't seem to be a valid option in the HAPI documentation, so might be best to move them up a level to prevent any future issues.

2020-01-13 16:06 UTC, markysoft commented on server/views/action.njk
> +    Action was {{ "successful" if actionResult.success else "unsuccessful" }}
Bit of a nitpick, but the mocked endpoint doesn't return anything other than success, so the page will never show unsuccessful

2020-01-13 16:06 UTC, markysoft commented on test/routes/action.test.js
> +  beforeAll(async () => {
The function was incorrectly marked as an `async` function in the project these were based on, might be worth removing the async from test functions that do not contain `await`

2020-01-13 16:06 UTC, markysoft commented on test/routes/healthy.test.js
> +  beforeAll(async () => {
A rogue async!

2020-01-13 16:06 UTC, markysoft commented on test/routes/healthz.test.js
> +  beforeAll(async () => {
Another unwanted async from the starter project...

2020-01-13 16:06 UTC, markysoft commented on test/routes/home.test.js
> +  beforeAll(async () => {
Another async on a standard function

2020-01-14 12:55 UTC, Matthew-Collins-Defra approved these changes
Looks good. All previous comments have been addresses, service is running on the correct url, tests all work.

2020-01-14 14:44 UTC, merged